refactor(cleancode): refactoring towards clean code
hexonet/whmcs-ispapi-widget-account pull request #24
Opened 2021-07-30 15:41 UTC by Rashad-j

2021-08-02 06:14 UTC, papakai requested changes

2021-08-02 06:14 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +        $this->currencyObject = new Currency();
This object isn't used somewhere (probably just by the balanceObject, as you are forwarding it in the constructor.
(I hope I have not overseen something).

If I am right, it makes more sense to move the currencyObject initialisation & handling into the Balance class.
You could either let the Balance class extend class Currency, or to use it as private var internally.

2021-08-02 06:14 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +                'Please install and activate the HEXONET ISPAPI Registrar Module v1.7.1 or higher. ' .
This error message is a relict of the past, Please change it to:

"Please install or upgrade  to the latest HEXONET ISPAPI Registrar Module. "

2021-08-02 06:14 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +        if (isset($data["balance"]) && isset($data['stats'])) {
Please be consistent with using single quotes and double quotes. In PHP, I suggest to use double quotes, in JS please single quotes.

2021-08-02 06:14 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +              '<div class="row" style="display: flex; flex-wrap: wrap; align-items: center;">' .
No inline styles please (i know this is just copy'n'paste). Please move CSS Code into the `AdminAreaHeadOutput` as shown in our last meeting.

e.g.

```
add_hook('AdminAreaHeadOutput', 1, function($vars) {
    if ($vars["pagetitle"] === "Dashboard") {
        return <<<HTML
            <style>
            ... your css code here
            </style>
HTML;
    }
});
```

2021-08-02 06:14 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +        return (
If there's no blocker, please rewrite this using HereDoc notation. You can assign function results to vars etc. before.

2021-08-02 06:14 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +        if ($userObjectStats["CODE"] == "200" || !empty($userObjectStats["PROPERTY"])) {
Please use strict comparision operator always over the unstrict one. So `===` over `==` to avoid type casts.

Our API Code is a String.

2021-08-02 06:14 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +        if ($accountsStatus["CODE"] == "200") { // is $accountsStatus["CODE"] string or int? if string use srtict type check !==
Please use `===` over `==`.

2021-08-02 09:27 UTC, Rashad-j reviewed
The reasons for keeping the variable name as a suffix in functions names was meant for distinguishing the variable from others. Say we want to add another variable, then if I use get, to get what? which variable? That's why we have getX, or setX. @papakai fyi. Let me know if you need to ignore this.

2021-08-02 09:51 UTC, Rashad-j commented on build/modules/widgets/ispapi_account.php
> +    public function getBalances(): ?array
ok, will do it this way.

2021-08-02 10:44 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +    protected $weight = 150; // What is 150, kilos? better use: private const WEIGHT_KILOS = 150;
title, description, weight, columns, cache, cacheExpiry, requiredPermission are properties inherited from [`\WHMCS\Module\AbstractWidget`](https://classdocs.whmcs.com/8.1/WHMCS/Module/AbstractWidget.html). The parent class has no setter methods for these, but using magic setters might then work. we followed just their widget sample available [here](https://developers.whmcs.com/advanced/widgets/). Getter methods are there, just in case you need them.

I fully agree, that this isn't as nice as it could be. What you can try:

a) Please cleanup the following properties as we use there the default values of the AbstractWidget class: `$description`, `$cacheExpiry`, `$columns`. `$requiredPermission`.

b) refactoring in direction of a constructor (anyone would then better know that this somehow deals with the parent class)

```
public function __construct() {
    $this->set("weight", 150);
    $this->set("title", "HEXONET ISPAPI Account Overview");
    $this->set("cache", false);
    parent::__construct();
}
```

Not sure if you have to call `parent::__construct` as AbstractWidget is an abstract class (a bit lack of knowledge on my end regarding OOP in PHP, so worth to add as comment in your PHP OOP task to get it documented later on).

If the above works, then you can also cleanup the declaration of the protected properties `$title`, `$weight`, `$cache` in our class. Otherwise, you'll have to leave it as it is.

HTH

2021-08-02 12:00 UTC, Rashad-j commented on build/modules/widgets/ispapi_account.php
> +        $this->currencyObject = new Currency();
Ok, as you want, both cases are possible. But in general composition is preferred over inheritance in clean code.

2021-08-02 12:03 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +        $this->currencyObject = new Currency();
ok, so we follow clean code best practices of course.

2021-08-03 07:32 UTC, Rashad-j commented on build/modules/widgets/ispapi_account.php
> +    protected $weight = 150; // What is 150, kilos? better use: private const WEIGHT_KILOS = 150;
Thank you for the elaboration, it helped me understand a bit more. The best solution I found was as follows: 
After a quick review of the parent class, I found 
``` protected $title = NULL;
    protected $description = NULL;
    protected $columns = 1;
    protected $weight = 100;
    protected $wrapper = true;
    protected $cache = false;
    protected $cachePerUser = false;
    protected $cacheExpiry = 3600;
    protected $requiredPermission = "";
    protected $draggable = true;
    protected $adminUser = NULL; 
```
Therefore, I only overwrote the needed properties in child class accordingly, without the need to create magic setter functions. 
PS, the parent class does not have `__construct` function, as per the nulled version.

2021-08-03 08:22 UTC, papakai requested changes

2021-08-03 08:22 UTC, papakai commented on .gitignore
> +!build/modules/widgets/*
Again, this line shouldn't be necessary. The whole build folder and all its contents have to be .gitignored.
Otherwise provide your insights why keeping that line is mandatory.

2021-08-03 08:22 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +use WHMCS\Module\Registrar\Ispapi\Helper;
Helper class is also not in use. Please cleanup. See another related comment below, for further understanding.

```
use WHMCS\Module\Registrar\Ispapi\Helper;
```

2021-08-03 08:22 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +        if (class_exists(Helper::class)) {
As you're cleaning up the Helper class, please replace this line by

```
if (class_exists(Ispapi::class)) {
```

Probably a relict of the past.

2021-08-03 08:22 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +    public function getStatisticsDataAsHTML(): ?string
maybe a shorter function name is `toHTML`?

2021-08-03 08:29 UTC, Rashad-j commented on .gitignore
> +!build/modules/widgets/*
This line is necessary so that we can have a copy of the code on git, e.g. this PR won't be possible unless I push the source code somewhere. Otherwise, I'll have to create the zip file, then you have to download to see the content.

2021-08-03 10:50 UTC, Rashad-j commented on .gitignore
> +!build/modules/widgets/*
I think there was a misunderstanding: your previous comment was "Widget's Source Code has to be located under /modules/widgets (i am fine with leaving it as single file in root dir too)." I was thinking you are referring to the folders inside of build!! I now understand. I will change the file directly in /modules/widgets. Sorry, I just got confused.

2021-08-04 07:21 UTC, papakai requested changes

2021-08-04 07:21 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +    public function generateOutput($data)
Missing type for $data? This is at least something you address in "Clean Code"

2021-08-04 07:36 UTC, Rashad-j commented on build/modules/widgets/ispapi_account.php
> +    public function generateOutput($data)
The reason for not setting the type was that WHMCS want it to be compatible with the parent class:
```
Whoops\Exception\ErrorException: Declaration of WHMCS\Module\Widget\IspapiAccountWidget::generateOutput(array $data) must be compatible with WHMCS\Module\AbstractWidget::generateOutput($data) in /var/www/whmcsdev1/modules/widgets/ispapi_account.php:116
```

2021-08-04 07:56 UTC, papakai commented on build/modules/widgets/ispapi_account.php
> +    public function generateOutput($data)
ok, fine then.

Looks like their docs are then even wrong:
https://classdocs.whmcs.com/8.1/WHMCS/Module/AbstractWidget.html#method_generateOutput

That's why I asked.

2021-08-04 13:34 UTC, papakai requested changes

2021-08-04 13:34 UTC, papakai commented on modules/widgets/ispapi_account.php
> +    public function getStatisticsDataAsHTML(): ?string
why not `toHTML` as requested before? You just marked this as resolved...

2021-08-04 13:37 UTC, papakai requested changes

2021-08-04 13:37 UTC, papakai commented on modules/widgets/ispapi_account.php
>  use WHMCS\Module\Registrar\Ispapi\Helper;
Please drop the Helper class as requested in my previous review. it is just used for an class existance check somewhere in code, there please replace it with the "Ispapi" class.

2021-08-05 05:58 UTC, Rashad-j commented on modules/widgets/ispapi_account.php
> +    public function getStatisticsDataAsHTML(): ?string
This was already done, but because the symbolic link was broken and I had to copy the content from whmcs to git folder.

2021-08-05 05:58 UTC, Rashad-j commented on modules/widgets/ispapi_account.php
>  use WHMCS\Module\Registrar\Ispapi\Helper;
This was already done, again because of the symbolic link was broken.

2021-08-05 05:59 UTC, papakai commented on modules/widgets/ispapi_account.php
> +    public function getStatisticsDataAsHTML(): ?string
well, we need to get this up and running as expected on your device - so having symbolic links working.
I am working on a daily base with that, saving so much time!

2021-08-05 11:37 UTC, merged

2021-08-05 11:38 UTC, papakai commented
:tada: This PR is included in version 3.1.2 :tada:

The release is available on [GitHub release](https://github.com/hexonet/whmcs-ispapi-widget-account/releases/tag/v3.1.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: